ARG CUDA_V=10.0

FROM nvidia/cuda:${CUDA_V}-devel
MAINTAINER Jesper Dramsch <jesper@dramsch.net>

LABEL Description="Madagascar cuda"

ENV CUDA_VERSION ${CUDA_V}

# Use /data as the persistent storage
VOLUME ["/data"]


ENV CUDA_VERSION ${CUDA_V}
ENV RSFROOT /root/madagascar
ENV RSF_DATASERVER	ftp://egl.beg.utexas.edu/
ENV RSFDOC	$RSFROOT/doc
ENV RSFFIGS	$RSFROOT/figs
ENV RSFALTFIGS	$RSFFIGS
ENV RSFMEMSIZE	100
ENV RSFSRC	undefined
ENV TMPDATAPATH	$DATAPATH
ENV LATEX2HTML	undefined
ENV DATAPATH /data

RUN apt-get update && apt-get install -y --no-install-recommends \
      ca-certificates \
      libxaw7-dev \
      freeglut3-dev \
      libnetpbm10-dev \
      libgd-dev \
      libplplot-dev \
      libavcodec-dev \
      libcairo2-dev \
      libjpeg-dev \
      swig \
      python-dev \
      python-numpy \
      g++ \
      gfortran \
      libopenmpi-dev\
      libfftw3-dev \
      libsuitesparse-dev \
      python-epydoc \
      scons \
      git \
      emacs25 \
      openmpi-bin \
      cuda-command-line-tools-9-0 \
      wget \
      && git clone https://github.com/ahay/src ${RSFROOT}/src \
      && cd ${RSFROOT}/src \
      && ./configure API=c++,fortran-90 --prefix=${RSFROOT} \
      && make; make install && make clean \
      && rm -rf ${RSFROOT}/src \
      && rm -rf /var/lib/apt/lists \
      && apt-get autoremove -y \
      && apt-get autoclean -y \
      && echo "source &{RSFROOT}/share/madagascar/etc/env.sh" >> $HOME/.bash_profile
